# Generated by Django 2.2.3 on 2019-08-11 15:25

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='project',
            managers=[
                ('projects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FilePathField(path='/img/'),
        ),
    ]
